name: whisperenv
dependencies:
  - python=3.10
  - pip
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-lru
  - attrs
  - babel
  - beautifulsoup4
  - bleach
  - brotli
  - cached-property
  - certifi
  - cffi
  - charset-normalizer
  - comm
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - exceptiongroup
  - executing
  - fastjsonschema
  - filelock
  - fqdn
  - fsspec=2024.10.0
  - gmpy2
  - h11
  - h2
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - idna
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - isoduration
  - jedi
  - jinja2
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jupyter-events
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - llvmlite=0.43.0
  - markupsafe
  - matplotlib-inline
  - mistune
  - mkl-service=2.4.0
  - mkl_fft
  - mkl_random
  - more-itertools=10.5.0
  - mpmath
  - nbclient
  - nbconvert
  - nbformat
  - nest_asyncio
  - networkx
  - notebook
  - notebook_shim
  - numba=0.60.0
  - numpy
  - openai-whisper
  - overrides
  - packaging
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pkgutil_resolve_name
  - platformdirs
  - prometheus_client
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pysocks
  - python-dateutil
  - python-json-logger
  - pytz
  - pyyaml
  - pyzmq
  - referencing
  - regex=2024.11.6
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - send2trash
  - six
  - sniffio
  - soupsieve
  - stack-data
  - sympy=1.13.1
  - terminado
  - tiktoken=0.8.0
  - tinycss2
  - tomli
  - torch=2.5.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado
  - tqdm=4.67.1
  - traitlets
  - triton=3.1.0
  - types-python-dateutil
  - typing_extensions
  - typing_utils
  - uri-template
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - zipp
